### ISSUE TITLE
Create wrapper function to run Abimo.exe

### ISSUE THREAD

**Issue by hsonne** [KWB-R/kwb.abimo#5]
This should be possible:
```
# Define some reference input file
input_file <- "~/qt-projects/abimo/data/abimo_2019_mitstrassen.dbf"

# Define some reference config file
config_file <- "~/qt-projects/abimo/data/config.xml"

# Read input data from reference file
input_data <- foreign::read.dbf(input_file)

# Read configuration file into list
config <- read_config(config_file)

# Modify the input data by modifying the data frame...
# Take care! Make sure that integer columns keep integer, therefore use "L" here!
input_data$REGENJA <- 600L

# Modify the configuration by modifying the list...
config$Infiltrationsfaktoren$Dachflaechen <- 0.2

# Either run Abimo by giving the paths to the files
result1 <- run_abimo(input_file = input_file, config_file = config_file)

# Or run Abimo by giving the R data structures
result2 <- run_abimo(input_data = input_data, config = config)

# In each case, the result is a data frame, containing the data from the dbf 
# file that was written by the Abimo executable
```
## Extra feature to validate the Bagrov calculation

```
# Let Abimo.exe output results of the Bagrov calculation
bagrov_lines <- kwb.abimo::run_abimo_command_line("--write-bagrov-table")

# Convert the text lines to a data frame
bagrov <- read.table(text = bagrov_lines, header = TRUE, sep = ",")
```

**Comment by LukasGue** [comment]
### My comment about input data

1. Did you maybe mean output file by the following code snippet? Because at the moment there is only one input file for abimo, right? (e.g., 'x_in_2019.dbf')
```
# Define some reference input file
input_file <- "~/qt-projects/abimo/data/abimo_2019_mitstrassen.dbf"
```
```
# Read input data from reference file
input_data <- foreign::read.dbf(input_file)
```

### My comment about rainfall modification

This is a very important point! Maybe we can also think about doing the same for the potential evaporation data.
```
# Modify the input data
input_data$REGENJA <- 600
```
And how about coupling the abimo wrapper with the R-scipts:
- [abimo_new_climate_data.R](https://github.com/KWB-R/kwb.abimo/blob/master/inst/extdata/scripts/abimo_new_climate_data.R)
- [prepare_abimo_scenarios.R](https://github.com/KWB-R/kwb.abimo/blob/master/inst/extdata/scripts/prepare_abimo_scenarios.R)
- [abimo_evaluate.R](https://github.com/KWB-R/kwb.abimo/blob/master/inst/extdata/scripts/abimo_evaluate.R)

**Comment by hsonne** [comment]
In general, everything that allows to simplify the usage of Abimo or the evaluation of its result (e.g. plotting) should go into kwb.abimo. Everything that is specific to a project should go into a project specific package (that we do not have so far). We could think of a repository amarex.scripts.

**Comment by hsonne** [comment]
Since #6 on the dev branch
